version: '3'

services:
  backend:
    build:
      context: ./go-weed-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./react-weed-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8081
